// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function DownloadFile(arg1) {
  return window['go']['main']['App']['DownloadFile'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function OpenDownloadPath() {
  return window['go']['main']['App']['OpenDownloadPath']();
}

export function OpenExplorer(arg1) {
  return window['go']['main']['App']['OpenExplorer'](arg1);
}

export function SearchPackage(arg1) {
  return window['go']['main']['App']['SearchPackage'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
