// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';
import {github} from '../models';

export function DownloadFile(arg1:string):Promise<void>;

export function GetSettings():Promise<main.ScorpionSettings>;

export function Greet(arg1:string):Promise<string>;

export function OpenDownloadPath():Promise<void>;

export function OpenExplorer(arg1:string):Promise<void>;

export function SearchPackage(arg1:string):Promise<Array<github.Repository>>;

export function UpdateSettings(arg1:main.ScorpionSettings):Promise<void>;
